# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dugout/v1/common.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ugout/v1/common.proto\x12\tdugout.v1\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"S\n\x0fPlayerReference\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rjersey_number\x18\x03 \x01(\t\x12\x0f\n\x07team_id\x18\x04 \x01(\t*M\n\x08TeamSide\x12\x19\n\x15TEAM_SIDE_UNSPECIFIED\x10\x00\x12\x12\n\x0eTEAM_SIDE_HOME\x10\x01\x12\x12\n\x0eTEAM_SIDE_AWAY\x10\x02\x42KZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dugout.v1.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1'
  _globals['_TEAMSIDE']._serialized_start=190
  _globals['_TEAMSIDE']._serialized_end=267
  _globals['_BOUNDINGBOX']._serialized_start=37
  _globals['_BOUNDINGBOX']._serialized_end=103
  _globals['_PLAYERREFERENCE']._serialized_start=105
  _globals['_PLAYERREFERENCE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
