# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dugout/v1/cv_observation.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dugout.v1 import common_pb2 as dugout_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64ugout/v1/cv_observation.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16\x64ugout/v1/common.proto\"\x8c\x01\n\x13JerseyNumberPayload\x12\x15\n\rjersey_number\x18\x01 \x01(\t\x12&\n\tteam_side\x18\x02 \x01(\x0e\x32\x13.dugout.v1.TeamSide\x12$\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x16.dugout.v1.BoundingBox\x12\x10\n\x08track_id\x18\x04 \x01(\t\"{\n\x19PlayerLocalizationPayload\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12$\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32\x16.dugout.v1.BoundingBox\x12&\n\tteam_side\x18\x03 \x01(\x0e\x32\x13.dugout.v1.TeamSide\"?\n\rModelMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\t\"\xdc\x02\n\rCvObservation\x12\x16\n\x0eobservation_id\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\t\x12\x11\n\tcamera_id\x18\x03 \x01(\t\x12/\n\x0bobserved_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10observation_type\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x01\x12\'\n\x05model\x18\x07 \x01(\x0b\x32\x18.dugout.v1.ModelMetadata\x12\x37\n\rjersey_number\x18\x08 \x01(\x0b\x32\x1e.dugout.v1.JerseyNumberPayloadH\x00\x12\x43\n\x13player_localization\x18\t \x01(\x0b\x32$.dugout.v1.PlayerLocalizationPayloadH\x00\x42\t\n\x07payloadBKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dugout.v1.cv_observation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1'
  _globals['_JERSEYNUMBERPAYLOAD']._serialized_start=103
  _globals['_JERSEYNUMBERPAYLOAD']._serialized_end=243
  _globals['_PLAYERLOCALIZATIONPAYLOAD']._serialized_start=245
  _globals['_PLAYERLOCALIZATIONPAYLOAD']._serialized_end=368
  _globals['_MODELMETADATA']._serialized_start=370
  _globals['_MODELMETADATA']._serialized_end=433
  _globals['_CVOBSERVATION']._serialized_start=436
  _globals['_CVOBSERVATION']._serialized_end=784
# @@protoc_insertion_point(module_scope)
