# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dugout/v1/game_state.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64ugout/v1/game_state.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x04\n\tGameState\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\r\n\x05\x62\x61lls\x18\x02 \x01(\x05\x12\x0f\n\x07strikes\x18\x03 \x01(\x05\x12\x0c\n\x04outs\x18\x04 \x01(\x05\x12\x12\n\nhome_score\x18\x05 \x01(\x05\x12\x12\n\naway_score\x18\x06 \x01(\x05\x12\x0e\n\x06inning\x18\x07 \x01(\x05\x12\x0e\n\x06is_top\x18\x08 \x01(\x08\x12\x17\n\x0frunner_on_first\x18\t \x01(\x08\x12!\n\x19runner_on_first_player_id\x18\n \x01(\t\x12\x18\n\x10runner_on_second\x18\x0b \x01(\x08\x12\"\n\x1arunner_on_second_player_id\x18\x0c \x01(\t\x12\x17\n\x0frunner_on_third\x18\r \x01(\x08\x12!\n\x19runner_on_third_player_id\x18\x0e \x01(\t\x12\x18\n\x10\x61\x63tive_batter_id\x18\x0f \x01(\t\x12\x19\n\x11\x61\x63tive_pitcher_id\x18\x10 \x01(\t\x12\x1a\n\x12\x62\x61tting_index_home\x18\x11 \x01(\x05\x12\x1a\n\x12\x62\x61tting_index_away\x18\x12 \x01(\x05\x12\x1a\n\x12game_clock_seconds\x18\x13 \x01(\x05\x12\x18\n\x10is_clock_running\x18\x14 \x01(\x08\x12\x15\n\rlast_event_id\x18\x15 \x01(\t\x12.\n\nupdated_at\x18\x16 \x01(\x0b\x32\x1a.google.protobuf.TimestampBKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dugout.v1.game_state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1'
  _globals['_GAMESTATE']._serialized_start=75
  _globals['_GAMESTATE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
