// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/audit.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // e.g. "game_start", "manual_override", "failed_command"
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`          // e.g. "system", "manager_user_id"
	EntityType    string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // e.g. "game_event", "cv_observation", "production_command"
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // Raw JSON for arbitrary structure storage
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_dugout_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_dugout_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRecord) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditRecord) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *AuditRecord) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AuditRecord) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditRecord) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditRecord) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuditRecord) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *AuditRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dugout_v1_audit_proto protoreflect.FileDescriptor

const file_dugout_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x15dugout/v1/audit.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x02\n" +
	"\vAuditRecord\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\fpayload_json\x18\b \x01(\tR\vpayloadJson\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_audit_proto_rawDescOnce sync.Once
	file_dugout_v1_audit_proto_rawDescData []byte
)

func file_dugout_v1_audit_proto_rawDescGZIP() []byte {
	file_dugout_v1_audit_proto_rawDescOnce.Do(func() {
		file_dugout_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_audit_proto_rawDesc), len(file_dugout_v1_audit_proto_rawDesc)))
	})
	return file_dugout_v1_audit_proto_rawDescData
}

var file_dugout_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dugout_v1_audit_proto_goTypes = []any{
	(*AuditRecord)(nil),           // 0: dugout.v1.AuditRecord
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_dugout_v1_audit_proto_depIdxs = []int32{
	1, // 0: dugout.v1.AuditRecord.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dugout_v1_audit_proto_init() }
func file_dugout_v1_audit_proto_init() {
	if File_dugout_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_audit_proto_rawDesc), len(file_dugout_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_audit_proto_goTypes,
		DependencyIndexes: file_dugout_v1_audit_proto_depIdxs,
		MessageInfos:      file_dugout_v1_audit_proto_msgTypes,
	}.Build()
	File_dugout_v1_audit_proto = out.File
	file_dugout_v1_audit_proto_goTypes = nil
	file_dugout_v1_audit_proto_depIdxs = nil
}
