// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/common.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamSide int32

const (
	TeamSide_TEAM_SIDE_UNSPECIFIED TeamSide = 0
	TeamSide_TEAM_SIDE_HOME        TeamSide = 1
	TeamSide_TEAM_SIDE_AWAY        TeamSide = 2
)

// Enum value maps for TeamSide.
var (
	TeamSide_name = map[int32]string{
		0: "TEAM_SIDE_UNSPECIFIED",
		1: "TEAM_SIDE_HOME",
		2: "TEAM_SIDE_AWAY",
	}
	TeamSide_value = map[string]int32{
		"TEAM_SIDE_UNSPECIFIED": 0,
		"TEAM_SIDE_HOME":        1,
		"TEAM_SIDE_AWAY":        2,
	}
)

func (x TeamSide) Enum() *TeamSide {
	p := new(TeamSide)
	*p = x
	return p
}

func (x TeamSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamSide) Descriptor() protoreflect.EnumDescriptor {
	return file_dugout_v1_common_proto_enumTypes[0].Descriptor()
}

func (TeamSide) Type() protoreflect.EnumType {
	return &file_dugout_v1_common_proto_enumTypes[0]
}

func (x TeamSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamSide.Descriptor instead.
func (TeamSide) EnumDescriptor() ([]byte, []int) {
	return file_dugout_v1_common_proto_rawDescGZIP(), []int{0}
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`           // Normalized top-left x (0.0 - 1.0)
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`           // Normalized top-left y (0.0 - 1.0)
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`   // Normalized width (0.0 - 1.0)
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"` // Normalized height (0.0 - 1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_dugout_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_dugout_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type PlayerReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	JerseyNumber  string                 `protobuf:"bytes,3,opt,name=jersey_number,json=jerseyNumber,proto3" json:"jersey_number,omitempty"`
	TeamId        string                 `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReference) Reset() {
	*x = PlayerReference{}
	mi := &file_dugout_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReference) ProtoMessage() {}

func (x *PlayerReference) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReference.ProtoReflect.Descriptor instead.
func (*PlayerReference) Descriptor() ([]byte, []int) {
	return file_dugout_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerReference) GetJerseyNumber() string {
	if x != nil {
		return x.JerseyNumber
	}
	return ""
}

func (x *PlayerReference) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

var File_dugout_v1_common_proto protoreflect.FileDescriptor

const file_dugout_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16dugout/v1/common.proto\x12\tdugout.v1\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\"s\n" +
	"\x0fPlayerReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rjersey_number\x18\x03 \x01(\tR\fjerseyNumber\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\tR\x06teamId*M\n" +
	"\bTeamSide\x12\x19\n" +
	"\x15TEAM_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTEAM_SIDE_HOME\x10\x01\x12\x12\n" +
	"\x0eTEAM_SIDE_AWAY\x10\x02BKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_common_proto_rawDescOnce sync.Once
	file_dugout_v1_common_proto_rawDescData []byte
)

func file_dugout_v1_common_proto_rawDescGZIP() []byte {
	file_dugout_v1_common_proto_rawDescOnce.Do(func() {
		file_dugout_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_common_proto_rawDesc), len(file_dugout_v1_common_proto_rawDesc)))
	})
	return file_dugout_v1_common_proto_rawDescData
}

var file_dugout_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dugout_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dugout_v1_common_proto_goTypes = []any{
	(TeamSide)(0),           // 0: dugout.v1.TeamSide
	(*BoundingBox)(nil),     // 1: dugout.v1.BoundingBox
	(*PlayerReference)(nil), // 2: dugout.v1.PlayerReference
}
var file_dugout_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dugout_v1_common_proto_init() }
func file_dugout_v1_common_proto_init() {
	if File_dugout_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_common_proto_rawDesc), len(file_dugout_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_common_proto_goTypes,
		DependencyIndexes: file_dugout_v1_common_proto_depIdxs,
		EnumInfos:         file_dugout_v1_common_proto_enumTypes,
		MessageInfos:      file_dugout_v1_common_proto_msgTypes,
	}.Build()
	File_dugout_v1_common_proto = out.File
	file_dugout_v1_common_proto_goTypes = nil
	file_dugout_v1_common_proto_depIdxs = nil
}
