// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/cv_observation.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JerseyNumberPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JerseyNumber  string                 `protobuf:"bytes,1,opt,name=jersey_number,json=jerseyNumber,proto3" json:"jersey_number,omitempty"`
	TeamSide      TeamSide               `protobuf:"varint,2,opt,name=team_side,json=teamSide,proto3,enum=dugout.v1.TeamSide" json:"team_side,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	TrackId       string                 `protobuf:"bytes,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JerseyNumberPayload) Reset() {
	*x = JerseyNumberPayload{}
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JerseyNumberPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JerseyNumberPayload) ProtoMessage() {}

func (x *JerseyNumberPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JerseyNumberPayload.ProtoReflect.Descriptor instead.
func (*JerseyNumberPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_cv_observation_proto_rawDescGZIP(), []int{0}
}

func (x *JerseyNumberPayload) GetJerseyNumber() string {
	if x != nil {
		return x.JerseyNumber
	}
	return ""
}

func (x *JerseyNumberPayload) GetTeamSide() TeamSide {
	if x != nil {
		return x.TeamSide
	}
	return TeamSide_TEAM_SIDE_UNSPECIFIED
}

func (x *JerseyNumberPayload) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *JerseyNumberPayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type PlayerLocalizationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	TeamSide      TeamSide               `protobuf:"varint,3,opt,name=team_side,json=teamSide,proto3,enum=dugout.v1.TeamSide" json:"team_side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLocalizationPayload) Reset() {
	*x = PlayerLocalizationPayload{}
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLocalizationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLocalizationPayload) ProtoMessage() {}

func (x *PlayerLocalizationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLocalizationPayload.ProtoReflect.Descriptor instead.
func (*PlayerLocalizationPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_cv_observation_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLocalizationPayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *PlayerLocalizationPayload) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *PlayerLocalizationPayload) GetTeamSide() TeamSide {
	if x != nil {
		return x.TeamSide
	}
	return TeamSide_TEAM_SIDE_UNSPECIFIED
}

type ModelMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_dugout_v1_cv_observation_proto_rawDescGZIP(), []int{2}
}

func (x *ModelMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelMetadata) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type CvObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObservationId   string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	GameId          string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CameraId        string                 `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ObservationType string                 `protobuf:"bytes,5,opt,name=observation_type,json=observationType,proto3" json:"observation_type,omitempty"` // e.g. "jersey_number", "player_localization"
	Confidence      float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Model           *ModelMetadata         `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CvObservation_JerseyNumber
	//	*CvObservation_PlayerLocalization
	Payload       isCvObservation_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CvObservation) Reset() {
	*x = CvObservation{}
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CvObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CvObservation) ProtoMessage() {}

func (x *CvObservation) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_cv_observation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CvObservation.ProtoReflect.Descriptor instead.
func (*CvObservation) Descriptor() ([]byte, []int) {
	return file_dugout_v1_cv_observation_proto_rawDescGZIP(), []int{3}
}

func (x *CvObservation) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *CvObservation) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CvObservation) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CvObservation) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *CvObservation) GetObservationType() string {
	if x != nil {
		return x.ObservationType
	}
	return ""
}

func (x *CvObservation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CvObservation) GetModel() *ModelMetadata {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *CvObservation) GetPayload() isCvObservation_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CvObservation) GetJerseyNumber() *JerseyNumberPayload {
	if x != nil {
		if x, ok := x.Payload.(*CvObservation_JerseyNumber); ok {
			return x.JerseyNumber
		}
	}
	return nil
}

func (x *CvObservation) GetPlayerLocalization() *PlayerLocalizationPayload {
	if x != nil {
		if x, ok := x.Payload.(*CvObservation_PlayerLocalization); ok {
			return x.PlayerLocalization
		}
	}
	return nil
}

type isCvObservation_Payload interface {
	isCvObservation_Payload()
}

type CvObservation_JerseyNumber struct {
	JerseyNumber *JerseyNumberPayload `protobuf:"bytes,8,opt,name=jersey_number,json=jerseyNumber,proto3,oneof"`
}

type CvObservation_PlayerLocalization struct {
	PlayerLocalization *PlayerLocalizationPayload `protobuf:"bytes,9,opt,name=player_localization,json=playerLocalization,proto3,oneof"`
}

func (*CvObservation_JerseyNumber) isCvObservation_Payload() {}

func (*CvObservation_PlayerLocalization) isCvObservation_Payload() {}

var File_dugout_v1_cv_observation_proto protoreflect.FileDescriptor

const file_dugout_v1_cv_observation_proto_rawDesc = "" +
	"\n" +
	"\x1edugout/v1/cv_observation.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16dugout/v1/common.proto\"\xb3\x01\n" +
	"\x13JerseyNumberPayload\x12#\n" +
	"\rjersey_number\x18\x01 \x01(\tR\fjerseyNumber\x120\n" +
	"\tteam_side\x18\x02 \x01(\x0e2\x13.dugout.v1.TeamSideR\bteamSide\x12*\n" +
	"\x04bbox\x18\x03 \x01(\v2\x16.dugout.v1.BoundingBoxR\x04bbox\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\tR\atrackId\"\x94\x01\n" +
	"\x19PlayerLocalizationPayload\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12*\n" +
	"\x04bbox\x18\x02 \x01(\v2\x16.dugout.v1.BoundingBoxR\x04bbox\x120\n" +
	"\tteam_side\x18\x03 \x01(\x0e2\x13.dugout.v1.TeamSideR\bteamSide\"W\n" +
	"\rModelMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\"\xcf\x03\n" +
	"\rCvObservation\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12)\n" +
	"\x10observation_type\x18\x05 \x01(\tR\x0fobservationType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12.\n" +
	"\x05model\x18\a \x01(\v2\x18.dugout.v1.ModelMetadataR\x05model\x12E\n" +
	"\rjersey_number\x18\b \x01(\v2\x1e.dugout.v1.JerseyNumberPayloadH\x00R\fjerseyNumber\x12W\n" +
	"\x13player_localization\x18\t \x01(\v2$.dugout.v1.PlayerLocalizationPayloadH\x00R\x12playerLocalizationB\t\n" +
	"\apayloadBKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_cv_observation_proto_rawDescOnce sync.Once
	file_dugout_v1_cv_observation_proto_rawDescData []byte
)

func file_dugout_v1_cv_observation_proto_rawDescGZIP() []byte {
	file_dugout_v1_cv_observation_proto_rawDescOnce.Do(func() {
		file_dugout_v1_cv_observation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_cv_observation_proto_rawDesc), len(file_dugout_v1_cv_observation_proto_rawDesc)))
	})
	return file_dugout_v1_cv_observation_proto_rawDescData
}

var file_dugout_v1_cv_observation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dugout_v1_cv_observation_proto_goTypes = []any{
	(*JerseyNumberPayload)(nil),       // 0: dugout.v1.JerseyNumberPayload
	(*PlayerLocalizationPayload)(nil), // 1: dugout.v1.PlayerLocalizationPayload
	(*ModelMetadata)(nil),             // 2: dugout.v1.ModelMetadata
	(*CvObservation)(nil),             // 3: dugout.v1.CvObservation
	(TeamSide)(0),                     // 4: dugout.v1.TeamSide
	(*BoundingBox)(nil),               // 5: dugout.v1.BoundingBox
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_dugout_v1_cv_observation_proto_depIdxs = []int32{
	4, // 0: dugout.v1.JerseyNumberPayload.team_side:type_name -> dugout.v1.TeamSide
	5, // 1: dugout.v1.JerseyNumberPayload.bbox:type_name -> dugout.v1.BoundingBox
	5, // 2: dugout.v1.PlayerLocalizationPayload.bbox:type_name -> dugout.v1.BoundingBox
	4, // 3: dugout.v1.PlayerLocalizationPayload.team_side:type_name -> dugout.v1.TeamSide
	6, // 4: dugout.v1.CvObservation.observed_at:type_name -> google.protobuf.Timestamp
	2, // 5: dugout.v1.CvObservation.model:type_name -> dugout.v1.ModelMetadata
	0, // 6: dugout.v1.CvObservation.jersey_number:type_name -> dugout.v1.JerseyNumberPayload
	1, // 7: dugout.v1.CvObservation.player_localization:type_name -> dugout.v1.PlayerLocalizationPayload
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dugout_v1_cv_observation_proto_init() }
func file_dugout_v1_cv_observation_proto_init() {
	if File_dugout_v1_cv_observation_proto != nil {
		return
	}
	file_dugout_v1_common_proto_init()
	file_dugout_v1_cv_observation_proto_msgTypes[3].OneofWrappers = []any{
		(*CvObservation_JerseyNumber)(nil),
		(*CvObservation_PlayerLocalization)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_cv_observation_proto_rawDesc), len(file_dugout_v1_cv_observation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_cv_observation_proto_goTypes,
		DependencyIndexes: file_dugout_v1_cv_observation_proto_depIdxs,
		MessageInfos:      file_dugout_v1_cv_observation_proto_msgTypes,
	}.Build()
	File_dugout_v1_cv_observation_proto = out.File
	file_dugout_v1_cv_observation_proto_goTypes = nil
	file_dugout_v1_cv_observation_proto_depIdxs = nil
}
