// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/game_state.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GameId                 string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Balls                  int32                  `protobuf:"varint,2,opt,name=balls,proto3" json:"balls,omitempty"`
	Strikes                int32                  `protobuf:"varint,3,opt,name=strikes,proto3" json:"strikes,omitempty"`
	Outs                   int32                  `protobuf:"varint,4,opt,name=outs,proto3" json:"outs,omitempty"`
	HomeScore              int32                  `protobuf:"varint,5,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore              int32                  `protobuf:"varint,6,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	Inning                 int32                  `protobuf:"varint,7,opt,name=inning,proto3" json:"inning,omitempty"`
	IsTop                  bool                   `protobuf:"varint,8,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	RunnerOnFirst          bool                   `protobuf:"varint,9,opt,name=runner_on_first,json=runnerOnFirst,proto3" json:"runner_on_first,omitempty"`
	RunnerOnFirstPlayerId  string                 `protobuf:"bytes,10,opt,name=runner_on_first_player_id,json=runnerOnFirstPlayerId,proto3" json:"runner_on_first_player_id,omitempty"`
	RunnerOnSecond         bool                   `protobuf:"varint,11,opt,name=runner_on_second,json=runnerOnSecond,proto3" json:"runner_on_second,omitempty"`
	RunnerOnSecondPlayerId string                 `protobuf:"bytes,12,opt,name=runner_on_second_player_id,json=runnerOnSecondPlayerId,proto3" json:"runner_on_second_player_id,omitempty"`
	RunnerOnThird          bool                   `protobuf:"varint,13,opt,name=runner_on_third,json=runnerOnThird,proto3" json:"runner_on_third,omitempty"`
	RunnerOnThirdPlayerId  string                 `protobuf:"bytes,14,opt,name=runner_on_third_player_id,json=runnerOnThirdPlayerId,proto3" json:"runner_on_third_player_id,omitempty"`
	ActiveBatterId         string                 `protobuf:"bytes,15,opt,name=active_batter_id,json=activeBatterId,proto3" json:"active_batter_id,omitempty"`
	ActivePitcherId        string                 `protobuf:"bytes,16,opt,name=active_pitcher_id,json=activePitcherId,proto3" json:"active_pitcher_id,omitempty"`
	BattingIndexHome       int32                  `protobuf:"varint,17,opt,name=batting_index_home,json=battingIndexHome,proto3" json:"batting_index_home,omitempty"` // Current 1-based index in the lineup (1-9)
	BattingIndexAway       int32                  `protobuf:"varint,18,opt,name=batting_index_away,json=battingIndexAway,proto3" json:"batting_index_away,omitempty"` // Current 1-based index in the lineup (1-9)
	GameClockSeconds       int32                  `protobuf:"varint,19,opt,name=game_clock_seconds,json=gameClockSeconds,proto3" json:"game_clock_seconds,omitempty"`
	IsClockRunning         bool                   `protobuf:"varint,20,opt,name=is_clock_running,json=isClockRunning,proto3" json:"is_clock_running,omitempty"`
	LastEventId            string                 `protobuf:"bytes,21,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_dugout_v1_game_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameState) GetBalls() int32 {
	if x != nil {
		return x.Balls
	}
	return 0
}

func (x *GameState) GetStrikes() int32 {
	if x != nil {
		return x.Strikes
	}
	return 0
}

func (x *GameState) GetOuts() int32 {
	if x != nil {
		return x.Outs
	}
	return 0
}

func (x *GameState) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *GameState) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *GameState) GetInning() int32 {
	if x != nil {
		return x.Inning
	}
	return 0
}

func (x *GameState) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *GameState) GetRunnerOnFirst() bool {
	if x != nil {
		return x.RunnerOnFirst
	}
	return false
}

func (x *GameState) GetRunnerOnFirstPlayerId() string {
	if x != nil {
		return x.RunnerOnFirstPlayerId
	}
	return ""
}

func (x *GameState) GetRunnerOnSecond() bool {
	if x != nil {
		return x.RunnerOnSecond
	}
	return false
}

func (x *GameState) GetRunnerOnSecondPlayerId() string {
	if x != nil {
		return x.RunnerOnSecondPlayerId
	}
	return ""
}

func (x *GameState) GetRunnerOnThird() bool {
	if x != nil {
		return x.RunnerOnThird
	}
	return false
}

func (x *GameState) GetRunnerOnThirdPlayerId() string {
	if x != nil {
		return x.RunnerOnThirdPlayerId
	}
	return ""
}

func (x *GameState) GetActiveBatterId() string {
	if x != nil {
		return x.ActiveBatterId
	}
	return ""
}

func (x *GameState) GetActivePitcherId() string {
	if x != nil {
		return x.ActivePitcherId
	}
	return ""
}

func (x *GameState) GetBattingIndexHome() int32 {
	if x != nil {
		return x.BattingIndexHome
	}
	return 0
}

func (x *GameState) GetBattingIndexAway() int32 {
	if x != nil {
		return x.BattingIndexAway
	}
	return 0
}

func (x *GameState) GetGameClockSeconds() int32 {
	if x != nil {
		return x.GameClockSeconds
	}
	return 0
}

func (x *GameState) GetIsClockRunning() bool {
	if x != nil {
		return x.IsClockRunning
	}
	return false
}

func (x *GameState) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

func (x *GameState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_dugout_v1_game_state_proto protoreflect.FileDescriptor

const file_dugout_v1_game_state_proto_rawDesc = "" +
	"\n" +
	"\x1adugout/v1/game_state.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x06\n" +
	"\tGameState\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05balls\x18\x02 \x01(\x05R\x05balls\x12\x18\n" +
	"\astrikes\x18\x03 \x01(\x05R\astrikes\x12\x12\n" +
	"\x04outs\x18\x04 \x01(\x05R\x04outs\x12\x1d\n" +
	"\n" +
	"home_score\x18\x05 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x06 \x01(\x05R\tawayScore\x12\x16\n" +
	"\x06inning\x18\a \x01(\x05R\x06inning\x12\x15\n" +
	"\x06is_top\x18\b \x01(\bR\x05isTop\x12&\n" +
	"\x0frunner_on_first\x18\t \x01(\bR\rrunnerOnFirst\x128\n" +
	"\x19runner_on_first_player_id\x18\n" +
	" \x01(\tR\x15runnerOnFirstPlayerId\x12(\n" +
	"\x10runner_on_second\x18\v \x01(\bR\x0erunnerOnSecond\x12:\n" +
	"\x1arunner_on_second_player_id\x18\f \x01(\tR\x16runnerOnSecondPlayerId\x12&\n" +
	"\x0frunner_on_third\x18\r \x01(\bR\rrunnerOnThird\x128\n" +
	"\x19runner_on_third_player_id\x18\x0e \x01(\tR\x15runnerOnThirdPlayerId\x12(\n" +
	"\x10active_batter_id\x18\x0f \x01(\tR\x0eactiveBatterId\x12*\n" +
	"\x11active_pitcher_id\x18\x10 \x01(\tR\x0factivePitcherId\x12,\n" +
	"\x12batting_index_home\x18\x11 \x01(\x05R\x10battingIndexHome\x12,\n" +
	"\x12batting_index_away\x18\x12 \x01(\x05R\x10battingIndexAway\x12,\n" +
	"\x12game_clock_seconds\x18\x13 \x01(\x05R\x10gameClockSeconds\x12(\n" +
	"\x10is_clock_running\x18\x14 \x01(\bR\x0eisClockRunning\x12\"\n" +
	"\rlast_event_id\x18\x15 \x01(\tR\vlastEventId\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_game_state_proto_rawDescOnce sync.Once
	file_dugout_v1_game_state_proto_rawDescData []byte
)

func file_dugout_v1_game_state_proto_rawDescGZIP() []byte {
	file_dugout_v1_game_state_proto_rawDescOnce.Do(func() {
		file_dugout_v1_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_game_state_proto_rawDesc), len(file_dugout_v1_game_state_proto_rawDesc)))
	})
	return file_dugout_v1_game_state_proto_rawDescData
}

var file_dugout_v1_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dugout_v1_game_state_proto_goTypes = []any{
	(*GameState)(nil),             // 0: dugout.v1.GameState
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_dugout_v1_game_state_proto_depIdxs = []int32{
	1, // 0: dugout.v1.GameState.updated_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dugout_v1_game_state_proto_init() }
func file_dugout_v1_game_state_proto_init() {
	if File_dugout_v1_game_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_game_state_proto_rawDesc), len(file_dugout_v1_game_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_game_state_proto_goTypes,
		DependencyIndexes: file_dugout_v1_game_state_proto_depIdxs,
		MessageInfos:      file_dugout_v1_game_state_proto_msgTypes,
	}.Build()
	File_dugout_v1_game_state_proto = out.File
	file_dugout_v1_game_state_proto_goTypes = nil
	file_dugout_v1_game_state_proto_depIdxs = nil
}
