// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/game_event.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PitchResultType int32

const (
	PitchResultType_PITCH_RESULT_TYPE_UNSPECIFIED     PitchResultType = 0
	PitchResultType_PITCH_RESULT_TYPE_BALL            PitchResultType = 1
	PitchResultType_PITCH_RESULT_TYPE_STRIKE_LOOKING  PitchResultType = 2
	PitchResultType_PITCH_RESULT_TYPE_STRIKE_SWINGING PitchResultType = 3
	PitchResultType_PITCH_RESULT_TYPE_FOUL            PitchResultType = 4
	PitchResultType_PITCH_RESULT_TYPE_PUT_IN_PLAY     PitchResultType = 5
	PitchResultType_PITCH_RESULT_TYPE_HIT_BY_PITCH    PitchResultType = 6
)

// Enum value maps for PitchResultType.
var (
	PitchResultType_name = map[int32]string{
		0: "PITCH_RESULT_TYPE_UNSPECIFIED",
		1: "PITCH_RESULT_TYPE_BALL",
		2: "PITCH_RESULT_TYPE_STRIKE_LOOKING",
		3: "PITCH_RESULT_TYPE_STRIKE_SWINGING",
		4: "PITCH_RESULT_TYPE_FOUL",
		5: "PITCH_RESULT_TYPE_PUT_IN_PLAY",
		6: "PITCH_RESULT_TYPE_HIT_BY_PITCH",
	}
	PitchResultType_value = map[string]int32{
		"PITCH_RESULT_TYPE_UNSPECIFIED":     0,
		"PITCH_RESULT_TYPE_BALL":            1,
		"PITCH_RESULT_TYPE_STRIKE_LOOKING":  2,
		"PITCH_RESULT_TYPE_STRIKE_SWINGING": 3,
		"PITCH_RESULT_TYPE_FOUL":            4,
		"PITCH_RESULT_TYPE_PUT_IN_PLAY":     5,
		"PITCH_RESULT_TYPE_HIT_BY_PITCH":    6,
	}
)

func (x PitchResultType) Enum() *PitchResultType {
	p := new(PitchResultType)
	*p = x
	return p
}

func (x PitchResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PitchResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_dugout_v1_game_event_proto_enumTypes[0].Descriptor()
}

func (PitchResultType) Type() protoreflect.EnumType {
	return &file_dugout_v1_game_event_proto_enumTypes[0]
}

func (x PitchResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PitchResultType.Descriptor instead.
func (PitchResultType) EnumDescriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{0}
}

type PlayOutcomeType int32

const (
	PlayOutcomeType_PLAY_OUTCOME_TYPE_UNSPECIFIED      PlayOutcomeType = 0
	PlayOutcomeType_PLAY_OUTCOME_TYPE_OUT              PlayOutcomeType = 1
	PlayOutcomeType_PLAY_OUTCOME_TYPE_SINGLE           PlayOutcomeType = 2
	PlayOutcomeType_PLAY_OUTCOME_TYPE_DOUBLE           PlayOutcomeType = 3
	PlayOutcomeType_PLAY_OUTCOME_TYPE_TRIPLE           PlayOutcomeType = 4
	PlayOutcomeType_PLAY_OUTCOME_TYPE_HOME_RUN         PlayOutcomeType = 5
	PlayOutcomeType_PLAY_OUTCOME_TYPE_WALK             PlayOutcomeType = 6
	PlayOutcomeType_PLAY_OUTCOME_TYPE_REACHED_ON_ERROR PlayOutcomeType = 7
	PlayOutcomeType_PLAY_OUTCOME_TYPE_FIELDERS_CHOICE  PlayOutcomeType = 8
)

// Enum value maps for PlayOutcomeType.
var (
	PlayOutcomeType_name = map[int32]string{
		0: "PLAY_OUTCOME_TYPE_UNSPECIFIED",
		1: "PLAY_OUTCOME_TYPE_OUT",
		2: "PLAY_OUTCOME_TYPE_SINGLE",
		3: "PLAY_OUTCOME_TYPE_DOUBLE",
		4: "PLAY_OUTCOME_TYPE_TRIPLE",
		5: "PLAY_OUTCOME_TYPE_HOME_RUN",
		6: "PLAY_OUTCOME_TYPE_WALK",
		7: "PLAY_OUTCOME_TYPE_REACHED_ON_ERROR",
		8: "PLAY_OUTCOME_TYPE_FIELDERS_CHOICE",
	}
	PlayOutcomeType_value = map[string]int32{
		"PLAY_OUTCOME_TYPE_UNSPECIFIED":      0,
		"PLAY_OUTCOME_TYPE_OUT":              1,
		"PLAY_OUTCOME_TYPE_SINGLE":           2,
		"PLAY_OUTCOME_TYPE_DOUBLE":           3,
		"PLAY_OUTCOME_TYPE_TRIPLE":           4,
		"PLAY_OUTCOME_TYPE_HOME_RUN":         5,
		"PLAY_OUTCOME_TYPE_WALK":             6,
		"PLAY_OUTCOME_TYPE_REACHED_ON_ERROR": 7,
		"PLAY_OUTCOME_TYPE_FIELDERS_CHOICE":  8,
	}
)

func (x PlayOutcomeType) Enum() *PlayOutcomeType {
	p := new(PlayOutcomeType)
	*p = x
	return p
}

func (x PlayOutcomeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayOutcomeType) Descriptor() protoreflect.EnumDescriptor {
	return file_dugout_v1_game_event_proto_enumTypes[1].Descriptor()
}

func (PlayOutcomeType) Type() protoreflect.EnumType {
	return &file_dugout_v1_game_event_proto_enumTypes[1]
}

func (x PlayOutcomeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayOutcomeType.Descriptor instead.
func (PlayOutcomeType) EnumDescriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{1}
}

type ClockAction int32

const (
	ClockAction_CLOCK_ACTION_UNSPECIFIED ClockAction = 0
	ClockAction_CLOCK_ACTION_START       ClockAction = 1
	ClockAction_CLOCK_ACTION_STOP        ClockAction = 2
	ClockAction_CLOCK_ACTION_RESET       ClockAction = 3
)

// Enum value maps for ClockAction.
var (
	ClockAction_name = map[int32]string{
		0: "CLOCK_ACTION_UNSPECIFIED",
		1: "CLOCK_ACTION_START",
		2: "CLOCK_ACTION_STOP",
		3: "CLOCK_ACTION_RESET",
	}
	ClockAction_value = map[string]int32{
		"CLOCK_ACTION_UNSPECIFIED": 0,
		"CLOCK_ACTION_START":       1,
		"CLOCK_ACTION_STOP":        2,
		"CLOCK_ACTION_RESET":       3,
	}
)

func (x ClockAction) Enum() *ClockAction {
	p := new(ClockAction)
	*p = x
	return p
}

func (x ClockAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClockAction) Descriptor() protoreflect.EnumDescriptor {
	return file_dugout_v1_game_event_proto_enumTypes[2].Descriptor()
}

func (ClockAction) Type() protoreflect.EnumType {
	return &file_dugout_v1_game_event_proto_enumTypes[2]
}

func (x ClockAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClockAction.Descriptor instead.
func (ClockAction) EnumDescriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{2}
}

type PitchResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        PitchResultType        `protobuf:"varint,1,opt,name=result,proto3,enum=dugout.v1.PitchResultType" json:"result,omitempty"`
	PitcherId     string                 `protobuf:"bytes,2,opt,name=pitcher_id,json=pitcherId,proto3" json:"pitcher_id,omitempty"`
	BatterId      string                 `protobuf:"bytes,3,opt,name=batter_id,json=batterId,proto3" json:"batter_id,omitempty"`
	SpeedMph      float32                `protobuf:"fixed32,4,opt,name=speed_mph,json=speedMph,proto3" json:"speed_mph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PitchResultPayload) Reset() {
	*x = PitchResultPayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PitchResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PitchResultPayload) ProtoMessage() {}

func (x *PitchResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PitchResultPayload.ProtoReflect.Descriptor instead.
func (*PitchResultPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{0}
}

func (x *PitchResultPayload) GetResult() PitchResultType {
	if x != nil {
		return x.Result
	}
	return PitchResultType_PITCH_RESULT_TYPE_UNSPECIFIED
}

func (x *PitchResultPayload) GetPitcherId() string {
	if x != nil {
		return x.PitcherId
	}
	return ""
}

func (x *PitchResultPayload) GetBatterId() string {
	if x != nil {
		return x.BatterId
	}
	return ""
}

func (x *PitchResultPayload) GetSpeedMph() float32 {
	if x != nil {
		return x.SpeedMph
	}
	return 0
}

type PlayOutcomePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PlayOutcomeType        `protobuf:"varint,1,opt,name=type,proto3,enum=dugout.v1.PlayOutcomeType" json:"type,omitempty"`
	RunsScored    int32                  `protobuf:"varint,2,opt,name=runs_scored,json=runsScored,proto3" json:"runs_scored,omitempty"`
	OutsRecorded  int32                  `protobuf:"varint,3,opt,name=outs_recorded,json=outsRecorded,proto3" json:"outs_recorded,omitempty"`
	BatterId      string                 `protobuf:"bytes,4,opt,name=batter_id,json=batterId,proto3" json:"batter_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayOutcomePayload) Reset() {
	*x = PlayOutcomePayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayOutcomePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayOutcomePayload) ProtoMessage() {}

func (x *PlayOutcomePayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayOutcomePayload.ProtoReflect.Descriptor instead.
func (*PlayOutcomePayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{1}
}

func (x *PlayOutcomePayload) GetType() PlayOutcomeType {
	if x != nil {
		return x.Type
	}
	return PlayOutcomeType_PLAY_OUTCOME_TYPE_UNSPECIFIED
}

func (x *PlayOutcomePayload) GetRunsScored() int32 {
	if x != nil {
		return x.RunsScored
	}
	return 0
}

func (x *PlayOutcomePayload) GetOutsRecorded() int32 {
	if x != nil {
		return x.OutsRecorded
	}
	return 0
}

func (x *PlayOutcomePayload) GetBatterId() string {
	if x != nil {
		return x.BatterId
	}
	return ""
}

func (x *PlayOutcomePayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InningTransitionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InningNumber  int32                  `protobuf:"varint,1,opt,name=inning_number,json=inningNumber,proto3" json:"inning_number,omitempty"`
	IsTop         bool                   `protobuf:"varint,2,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"` // true = top, false = bottom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InningTransitionPayload) Reset() {
	*x = InningTransitionPayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InningTransitionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InningTransitionPayload) ProtoMessage() {}

func (x *InningTransitionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InningTransitionPayload.ProtoReflect.Descriptor instead.
func (*InningTransitionPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{2}
}

func (x *InningTransitionPayload) GetInningNumber() int32 {
	if x != nil {
		return x.InningNumber
	}
	return 0
}

func (x *InningTransitionPayload) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

type SubstitutionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	PlayerInId    string                 `protobuf:"bytes,2,opt,name=player_in_id,json=playerInId,proto3" json:"player_in_id,omitempty"`
	PlayerOutId   string                 `protobuf:"bytes,3,opt,name=player_out_id,json=playerOutId,proto3" json:"player_out_id,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubstitutionPayload) Reset() {
	*x = SubstitutionPayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubstitutionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstitutionPayload) ProtoMessage() {}

func (x *SubstitutionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstitutionPayload.ProtoReflect.Descriptor instead.
func (*SubstitutionPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{3}
}

func (x *SubstitutionPayload) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SubstitutionPayload) GetPlayerInId() string {
	if x != nil {
		return x.PlayerInId
	}
	return ""
}

func (x *SubstitutionPayload) GetPlayerOutId() string {
	if x != nil {
		return x.PlayerOutId
	}
	return ""
}

func (x *SubstitutionPayload) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type ClockControlPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         ClockAction            `protobuf:"varint,1,opt,name=action,proto3,enum=dugout.v1.ClockAction" json:"action,omitempty"`
	SetTimeSeconds int32                  `protobuf:"varint,2,opt,name=set_time_seconds,json=setTimeSeconds,proto3" json:"set_time_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClockControlPayload) Reset() {
	*x = ClockControlPayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockControlPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockControlPayload) ProtoMessage() {}

func (x *ClockControlPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockControlPayload.ProtoReflect.Descriptor instead.
func (*ClockControlPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{4}
}

func (x *ClockControlPayload) GetAction() ClockAction {
	if x != nil {
		return x.Action
	}
	return ClockAction_CLOCK_ACTION_UNSPECIFIED
}

func (x *ClockControlPayload) GetSetTimeSeconds() int32 {
	if x != nil {
		return x.SetTimeSeconds
	}
	return 0
}

type GameCorrectionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balls         int32                  `protobuf:"varint,1,opt,name=balls,proto3" json:"balls,omitempty"`
	Strikes       int32                  `protobuf:"varint,2,opt,name=strikes,proto3" json:"strikes,omitempty"`
	Outs          int32                  `protobuf:"varint,3,opt,name=outs,proto3" json:"outs,omitempty"`
	HomeScore     int32                  `protobuf:"varint,4,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore     int32                  `protobuf:"varint,5,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCorrectionPayload) Reset() {
	*x = GameCorrectionPayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCorrectionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCorrectionPayload) ProtoMessage() {}

func (x *GameCorrectionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCorrectionPayload.ProtoReflect.Descriptor instead.
func (*GameCorrectionPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{5}
}

func (x *GameCorrectionPayload) GetBalls() int32 {
	if x != nil {
		return x.Balls
	}
	return 0
}

func (x *GameCorrectionPayload) GetStrikes() int32 {
	if x != nil {
		return x.Strikes
	}
	return 0
}

func (x *GameCorrectionPayload) GetOuts() int32 {
	if x != nil {
		return x.Outs
	}
	return 0
}

func (x *GameCorrectionPayload) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *GameCorrectionPayload) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *GameCorrectionPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ManualOverridePayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OverrideType     string                 `protobuf:"bytes,1,opt,name=override_type,json=overrideType,proto3" json:"override_type,omitempty"` // e.g. "confirm_player_identity"
	OriginalId       string                 `protobuf:"bytes,2,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`       // e.g. observation ID or command ID
	SelectedPlayerId string                 `protobuf:"bytes,3,opt,name=selected_player_id,json=selectedPlayerId,proto3" json:"selected_player_id,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManualOverridePayload) Reset() {
	*x = ManualOverridePayload{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualOverridePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualOverridePayload) ProtoMessage() {}

func (x *ManualOverridePayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualOverridePayload.ProtoReflect.Descriptor instead.
func (*ManualOverridePayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{6}
}

func (x *ManualOverridePayload) GetOverrideType() string {
	if x != nil {
		return x.OverrideType
	}
	return ""
}

func (x *ManualOverridePayload) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *ManualOverridePayload) GetSelectedPlayerId() string {
	if x != nil {
		return x.SelectedPlayerId
	}
	return ""
}

func (x *ManualOverridePayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GameEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	GameId         string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Source         string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // e.g. "referee_app", "manager_dashboard"
	SourceDeviceId string                 `protobuf:"bytes,4,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ReceivedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Sequence       int64                  `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Confidence     float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Authority      string                 `protobuf:"bytes,9,opt,name=authority,proto3" json:"authority,omitempty"` // "official" or "manager"
	CorrelationId  string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameEvent_PitchResult
	//	*GameEvent_PlayOutcome
	//	*GameEvent_InningTransition
	//	*GameEvent_Substitution
	//	*GameEvent_ClockControl
	//	*GameEvent_Correction
	//	*GameEvent_ManualOverride
	Payload       isGameEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_dugout_v1_game_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_game_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_dugout_v1_game_event_proto_rawDescGZIP(), []int{7}
}

func (x *GameEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GameEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GameEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

func (x *GameEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GameEvent) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *GameEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GameEvent) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *GameEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GameEvent) GetPayload() isGameEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameEvent) GetPitchResult() *PitchResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PitchResult); ok {
			return x.PitchResult
		}
	}
	return nil
}

func (x *GameEvent) GetPlayOutcome() *PlayOutcomePayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayOutcome); ok {
			return x.PlayOutcome
		}
	}
	return nil
}

func (x *GameEvent) GetInningTransition() *InningTransitionPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_InningTransition); ok {
			return x.InningTransition
		}
	}
	return nil
}

func (x *GameEvent) GetSubstitution() *SubstitutionPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_Substitution); ok {
			return x.Substitution
		}
	}
	return nil
}

func (x *GameEvent) GetClockControl() *ClockControlPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_ClockControl); ok {
			return x.ClockControl
		}
	}
	return nil
}

func (x *GameEvent) GetCorrection() *GameCorrectionPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_Correction); ok {
			return x.Correction
		}
	}
	return nil
}

func (x *GameEvent) GetManualOverride() *ManualOverridePayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_ManualOverride); ok {
			return x.ManualOverride
		}
	}
	return nil
}

type isGameEvent_Payload interface {
	isGameEvent_Payload()
}

type GameEvent_PitchResult struct {
	PitchResult *PitchResultPayload `protobuf:"bytes,11,opt,name=pitch_result,json=pitchResult,proto3,oneof"`
}

type GameEvent_PlayOutcome struct {
	PlayOutcome *PlayOutcomePayload `protobuf:"bytes,12,opt,name=play_outcome,json=playOutcome,proto3,oneof"`
}

type GameEvent_InningTransition struct {
	InningTransition *InningTransitionPayload `protobuf:"bytes,13,opt,name=inning_transition,json=inningTransition,proto3,oneof"`
}

type GameEvent_Substitution struct {
	Substitution *SubstitutionPayload `protobuf:"bytes,14,opt,name=substitution,proto3,oneof"`
}

type GameEvent_ClockControl struct {
	ClockControl *ClockControlPayload `protobuf:"bytes,15,opt,name=clock_control,json=clockControl,proto3,oneof"`
}

type GameEvent_Correction struct {
	Correction *GameCorrectionPayload `protobuf:"bytes,16,opt,name=correction,proto3,oneof"`
}

type GameEvent_ManualOverride struct {
	ManualOverride *ManualOverridePayload `protobuf:"bytes,17,opt,name=manual_override,json=manualOverride,proto3,oneof"`
}

func (*GameEvent_PitchResult) isGameEvent_Payload() {}

func (*GameEvent_PlayOutcome) isGameEvent_Payload() {}

func (*GameEvent_InningTransition) isGameEvent_Payload() {}

func (*GameEvent_Substitution) isGameEvent_Payload() {}

func (*GameEvent_ClockControl) isGameEvent_Payload() {}

func (*GameEvent_Correction) isGameEvent_Payload() {}

func (*GameEvent_ManualOverride) isGameEvent_Payload() {}

var File_dugout_v1_game_event_proto protoreflect.FileDescriptor

const file_dugout_v1_game_event_proto_rawDesc = "" +
	"\n" +
	"\x1adugout/v1/game_event.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16dugout/v1/common.proto\"\xa1\x01\n" +
	"\x12PitchResultPayload\x122\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1a.dugout.v1.PitchResultTypeR\x06result\x12\x1d\n" +
	"\n" +
	"pitcher_id\x18\x02 \x01(\tR\tpitcherId\x12\x1b\n" +
	"\tbatter_id\x18\x03 \x01(\tR\bbatterId\x12\x1b\n" +
	"\tspeed_mph\x18\x04 \x01(\x02R\bspeedMph\"\xc9\x01\n" +
	"\x12PlayOutcomePayload\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.dugout.v1.PlayOutcomeTypeR\x04type\x12\x1f\n" +
	"\vruns_scored\x18\x02 \x01(\x05R\n" +
	"runsScored\x12#\n" +
	"\routs_recorded\x18\x03 \x01(\x05R\foutsRecorded\x12\x1b\n" +
	"\tbatter_id\x18\x04 \x01(\tR\bbatterId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"U\n" +
	"\x17InningTransitionPayload\x12#\n" +
	"\rinning_number\x18\x01 \x01(\x05R\finningNumber\x12\x15\n" +
	"\x06is_top\x18\x02 \x01(\bR\x05isTop\"\x90\x01\n" +
	"\x13SubstitutionPayload\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12 \n" +
	"\fplayer_in_id\x18\x02 \x01(\tR\n" +
	"playerInId\x12\"\n" +
	"\rplayer_out_id\x18\x03 \x01(\tR\vplayerOutId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\"o\n" +
	"\x13ClockControlPayload\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.dugout.v1.ClockActionR\x06action\x12(\n" +
	"\x10set_time_seconds\x18\x02 \x01(\x05R\x0esetTimeSeconds\"\xb1\x01\n" +
	"\x15GameCorrectionPayload\x12\x14\n" +
	"\x05balls\x18\x01 \x01(\x05R\x05balls\x12\x18\n" +
	"\astrikes\x18\x02 \x01(\x05R\astrikes\x12\x12\n" +
	"\x04outs\x18\x03 \x01(\x05R\x04outs\x12\x1d\n" +
	"\n" +
	"home_score\x18\x04 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x05 \x01(\x05R\tawayScore\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xa3\x01\n" +
	"\x15ManualOverridePayload\x12#\n" +
	"\roverride_type\x18\x01 \x01(\tR\foverrideType\x12\x1f\n" +
	"\voriginal_id\x18\x02 \x01(\tR\n" +
	"originalId\x12,\n" +
	"\x12selected_player_id\x18\x03 \x01(\tR\x10selectedPlayerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x80\a\n" +
	"\tGameEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12(\n" +
	"\x10source_device_id\x18\x04 \x01(\tR\x0esourceDeviceId\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12;\n" +
	"\vreceived_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequence\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\tauthority\x18\t \x01(\tR\tauthority\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12B\n" +
	"\fpitch_result\x18\v \x01(\v2\x1d.dugout.v1.PitchResultPayloadH\x00R\vpitchResult\x12B\n" +
	"\fplay_outcome\x18\f \x01(\v2\x1d.dugout.v1.PlayOutcomePayloadH\x00R\vplayOutcome\x12Q\n" +
	"\x11inning_transition\x18\r \x01(\v2\".dugout.v1.InningTransitionPayloadH\x00R\x10inningTransition\x12D\n" +
	"\fsubstitution\x18\x0e \x01(\v2\x1e.dugout.v1.SubstitutionPayloadH\x00R\fsubstitution\x12E\n" +
	"\rclock_control\x18\x0f \x01(\v2\x1e.dugout.v1.ClockControlPayloadH\x00R\fclockControl\x12B\n" +
	"\n" +
	"correction\x18\x10 \x01(\v2 .dugout.v1.GameCorrectionPayloadH\x00R\n" +
	"correction\x12K\n" +
	"\x0fmanual_override\x18\x11 \x01(\v2 .dugout.v1.ManualOverridePayloadH\x00R\x0emanualOverrideB\t\n" +
	"\apayload*\x80\x02\n" +
	"\x0fPitchResultType\x12!\n" +
	"\x1dPITCH_RESULT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PITCH_RESULT_TYPE_BALL\x10\x01\x12$\n" +
	" PITCH_RESULT_TYPE_STRIKE_LOOKING\x10\x02\x12%\n" +
	"!PITCH_RESULT_TYPE_STRIKE_SWINGING\x10\x03\x12\x1a\n" +
	"\x16PITCH_RESULT_TYPE_FOUL\x10\x04\x12!\n" +
	"\x1dPITCH_RESULT_TYPE_PUT_IN_PLAY\x10\x05\x12\"\n" +
	"\x1ePITCH_RESULT_TYPE_HIT_BY_PITCH\x10\x06*\xb4\x02\n" +
	"\x0fPlayOutcomeType\x12!\n" +
	"\x1dPLAY_OUTCOME_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLAY_OUTCOME_TYPE_OUT\x10\x01\x12\x1c\n" +
	"\x18PLAY_OUTCOME_TYPE_SINGLE\x10\x02\x12\x1c\n" +
	"\x18PLAY_OUTCOME_TYPE_DOUBLE\x10\x03\x12\x1c\n" +
	"\x18PLAY_OUTCOME_TYPE_TRIPLE\x10\x04\x12\x1e\n" +
	"\x1aPLAY_OUTCOME_TYPE_HOME_RUN\x10\x05\x12\x1a\n" +
	"\x16PLAY_OUTCOME_TYPE_WALK\x10\x06\x12&\n" +
	"\"PLAY_OUTCOME_TYPE_REACHED_ON_ERROR\x10\a\x12%\n" +
	"!PLAY_OUTCOME_TYPE_FIELDERS_CHOICE\x10\b*r\n" +
	"\vClockAction\x12\x1c\n" +
	"\x18CLOCK_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CLOCK_ACTION_START\x10\x01\x12\x15\n" +
	"\x11CLOCK_ACTION_STOP\x10\x02\x12\x16\n" +
	"\x12CLOCK_ACTION_RESET\x10\x03BKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_game_event_proto_rawDescOnce sync.Once
	file_dugout_v1_game_event_proto_rawDescData []byte
)

func file_dugout_v1_game_event_proto_rawDescGZIP() []byte {
	file_dugout_v1_game_event_proto_rawDescOnce.Do(func() {
		file_dugout_v1_game_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_game_event_proto_rawDesc), len(file_dugout_v1_game_event_proto_rawDesc)))
	})
	return file_dugout_v1_game_event_proto_rawDescData
}

var file_dugout_v1_game_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dugout_v1_game_event_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_dugout_v1_game_event_proto_goTypes = []any{
	(PitchResultType)(0),            // 0: dugout.v1.PitchResultType
	(PlayOutcomeType)(0),            // 1: dugout.v1.PlayOutcomeType
	(ClockAction)(0),                // 2: dugout.v1.ClockAction
	(*PitchResultPayload)(nil),      // 3: dugout.v1.PitchResultPayload
	(*PlayOutcomePayload)(nil),      // 4: dugout.v1.PlayOutcomePayload
	(*InningTransitionPayload)(nil), // 5: dugout.v1.InningTransitionPayload
	(*SubstitutionPayload)(nil),     // 6: dugout.v1.SubstitutionPayload
	(*ClockControlPayload)(nil),     // 7: dugout.v1.ClockControlPayload
	(*GameCorrectionPayload)(nil),   // 8: dugout.v1.GameCorrectionPayload
	(*ManualOverridePayload)(nil),   // 9: dugout.v1.ManualOverridePayload
	(*GameEvent)(nil),               // 10: dugout.v1.GameEvent
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_dugout_v1_game_event_proto_depIdxs = []int32{
	0,  // 0: dugout.v1.PitchResultPayload.result:type_name -> dugout.v1.PitchResultType
	1,  // 1: dugout.v1.PlayOutcomePayload.type:type_name -> dugout.v1.PlayOutcomeType
	2,  // 2: dugout.v1.ClockControlPayload.action:type_name -> dugout.v1.ClockAction
	11, // 3: dugout.v1.GameEvent.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 4: dugout.v1.GameEvent.received_at:type_name -> google.protobuf.Timestamp
	3,  // 5: dugout.v1.GameEvent.pitch_result:type_name -> dugout.v1.PitchResultPayload
	4,  // 6: dugout.v1.GameEvent.play_outcome:type_name -> dugout.v1.PlayOutcomePayload
	5,  // 7: dugout.v1.GameEvent.inning_transition:type_name -> dugout.v1.InningTransitionPayload
	6,  // 8: dugout.v1.GameEvent.substitution:type_name -> dugout.v1.SubstitutionPayload
	7,  // 9: dugout.v1.GameEvent.clock_control:type_name -> dugout.v1.ClockControlPayload
	8,  // 10: dugout.v1.GameEvent.correction:type_name -> dugout.v1.GameCorrectionPayload
	9,  // 11: dugout.v1.GameEvent.manual_override:type_name -> dugout.v1.ManualOverridePayload
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_dugout_v1_game_event_proto_init() }
func file_dugout_v1_game_event_proto_init() {
	if File_dugout_v1_game_event_proto != nil {
		return
	}
	file_dugout_v1_common_proto_init()
	file_dugout_v1_game_event_proto_msgTypes[7].OneofWrappers = []any{
		(*GameEvent_PitchResult)(nil),
		(*GameEvent_PlayOutcome)(nil),
		(*GameEvent_InningTransition)(nil),
		(*GameEvent_Substitution)(nil),
		(*GameEvent_ClockControl)(nil),
		(*GameEvent_Correction)(nil),
		(*GameEvent_ManualOverride)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_game_event_proto_rawDesc), len(file_dugout_v1_game_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_game_event_proto_goTypes,
		DependencyIndexes: file_dugout_v1_game_event_proto_depIdxs,
		EnumInfos:         file_dugout_v1_game_event_proto_enumTypes,
		MessageInfos:      file_dugout_v1_game_event_proto_msgTypes,
	}.Build()
	File_dugout_v1_game_event_proto = out.File
	file_dugout_v1_game_event_proto_goTypes = nil
	file_dugout_v1_game_event_proto_depIdxs = nil
}
