// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dugout/v1/production_command.proto

package dugoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_QUEUED      CommandStatus = 1
	CommandStatus_COMMAND_STATUS_STARTED     CommandStatus = 2
	CommandStatus_COMMAND_STATUS_COMPLETED   CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_CANCELLED   CommandStatus = 5
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_QUEUED",
		2: "COMMAND_STATUS_STARTED",
		3: "COMMAND_STATUS_COMPLETED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_CANCELLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_QUEUED":      1,
		"COMMAND_STATUS_STARTED":     2,
		"COMMAND_STATUS_COMPLETED":   3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_CANCELLED":   5,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dugout_v1_production_command_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_dugout_v1_production_command_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{0}
}

type PlayWalkupMusicPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	FadeInMs      int32                  `protobuf:"varint,3,opt,name=fade_in_ms,json=fadeInMs,proto3" json:"fade_in_ms,omitempty"`
	MaxDurationMs int32                  `protobuf:"varint,4,opt,name=max_duration_ms,json=maxDurationMs,proto3" json:"max_duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayWalkupMusicPayload) Reset() {
	*x = PlayWalkupMusicPayload{}
	mi := &file_dugout_v1_production_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayWalkupMusicPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayWalkupMusicPayload) ProtoMessage() {}

func (x *PlayWalkupMusicPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_production_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayWalkupMusicPayload.ProtoReflect.Descriptor instead.
func (*PlayWalkupMusicPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{0}
}

func (x *PlayWalkupMusicPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayWalkupMusicPayload) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PlayWalkupMusicPayload) GetFadeInMs() int32 {
	if x != nil {
		return x.FadeInMs
	}
	return 0
}

func (x *PlayWalkupMusicPayload) GetMaxDurationMs() int32 {
	if x != nil {
		return x.MaxDurationMs
	}
	return 0
}

type UpdateScoreboardPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HomeScore       int32                  `protobuf:"varint,1,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore       int32                  `protobuf:"varint,2,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	Inning          int32                  `protobuf:"varint,3,opt,name=inning,proto3" json:"inning,omitempty"`
	IsTop           bool                   `protobuf:"varint,4,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	Balls           int32                  `protobuf:"varint,5,opt,name=balls,proto3" json:"balls,omitempty"`
	Strikes         int32                  `protobuf:"varint,6,opt,name=strikes,proto3" json:"strikes,omitempty"`
	Outs            int32                  `protobuf:"varint,7,opt,name=outs,proto3" json:"outs,omitempty"`
	BatterName      string                 `protobuf:"bytes,8,opt,name=batter_name,json=batterName,proto3" json:"batter_name,omitempty"`
	PitcherName     string                 `protobuf:"bytes,9,opt,name=pitcher_name,json=pitcherName,proto3" json:"pitcher_name,omitempty"`
	PitchSpeedMph   float32                `protobuf:"fixed32,10,opt,name=pitch_speed_mph,json=pitchSpeedMph,proto3" json:"pitch_speed_mph,omitempty"`
	DisplayTemplate string                 `protobuf:"bytes,11,opt,name=display_template,json=displayTemplate,proto3" json:"display_template,omitempty"` // 'batter_intro', 'pitcher_intro', 'count', etc.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateScoreboardPayload) Reset() {
	*x = UpdateScoreboardPayload{}
	mi := &file_dugout_v1_production_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreboardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreboardPayload) ProtoMessage() {}

func (x *UpdateScoreboardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_production_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreboardPayload.ProtoReflect.Descriptor instead.
func (*UpdateScoreboardPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateScoreboardPayload) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetInning() int32 {
	if x != nil {
		return x.Inning
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *UpdateScoreboardPayload) GetBalls() int32 {
	if x != nil {
		return x.Balls
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetStrikes() int32 {
	if x != nil {
		return x.Strikes
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetOuts() int32 {
	if x != nil {
		return x.Outs
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetBatterName() string {
	if x != nil {
		return x.BatterName
	}
	return ""
}

func (x *UpdateScoreboardPayload) GetPitcherName() string {
	if x != nil {
		return x.PitcherName
	}
	return ""
}

func (x *UpdateScoreboardPayload) GetPitchSpeedMph() float32 {
	if x != nil {
		return x.PitchSpeedMph
	}
	return 0
}

func (x *UpdateScoreboardPayload) GetDisplayTemplate() string {
	if x != nil {
		return x.DisplayTemplate
	}
	return ""
}

type GenerateCommentaryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TtsAssetId    string                 `protobuf:"bytes,2,opt,name=tts_asset_id,json=ttsAssetId,proto3" json:"tts_asset_id,omitempty"`
	PlayAudio     bool                   `protobuf:"varint,3,opt,name=play_audio,json=playAudio,proto3" json:"play_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCommentaryPayload) Reset() {
	*x = GenerateCommentaryPayload{}
	mi := &file_dugout_v1_production_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCommentaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCommentaryPayload) ProtoMessage() {}

func (x *GenerateCommentaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_production_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCommentaryPayload.ProtoReflect.Descriptor instead.
func (*GenerateCommentaryPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateCommentaryPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateCommentaryPayload) GetTtsAssetId() string {
	if x != nil {
		return x.TtsAssetId
	}
	return ""
}

func (x *GenerateCommentaryPayload) GetPlayAudio() bool {
	if x != nil {
		return x.PlayAudio
	}
	return false
}

type TriggerAlertPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertType     string                 `protobuf:"bytes,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // "low_cv_confidence", "duplicate_event", etc.
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // The ID of the event or observation causing the alert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerAlertPayload) Reset() {
	*x = TriggerAlertPayload{}
	mi := &file_dugout_v1_production_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerAlertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAlertPayload) ProtoMessage() {}

func (x *TriggerAlertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_production_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAlertPayload.ProtoReflect.Descriptor instead.
func (*TriggerAlertPayload) Descriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerAlertPayload) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *TriggerAlertPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerAlertPayload) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TriggerAlertPayload) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type ProductionCommand struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	CommandId                   string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	GameId                      string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CommandType                 string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // "play_walkup_music", "update_scoreboard", etc.
	Target                      string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                              // "music_adapter", "graphics_adapter", etc.
	CreatedAt                   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SourceEventIds              []string               `protobuf:"bytes,6,rep,name=source_event_ids,json=sourceEventIds,proto3" json:"source_event_ids,omitempty"`
	RequiresManagerConfirmation bool                   `protobuf:"varint,7,opt,name=requires_manager_confirmation,json=requiresManagerConfirmation,proto3" json:"requires_manager_confirmation,omitempty"`
	Status                      CommandStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=dugout.v1.CommandStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProductionCommand_PlayWalkupMusic
	//	*ProductionCommand_UpdateScoreboard
	//	*ProductionCommand_GenerateCommentary
	//	*ProductionCommand_TriggerAlert
	Payload       isProductionCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionCommand) Reset() {
	*x = ProductionCommand{}
	mi := &file_dugout_v1_production_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionCommand) ProtoMessage() {}

func (x *ProductionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dugout_v1_production_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionCommand.ProtoReflect.Descriptor instead.
func (*ProductionCommand) Descriptor() ([]byte, []int) {
	return file_dugout_v1_production_command_proto_rawDescGZIP(), []int{4}
}

func (x *ProductionCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ProductionCommand) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ProductionCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *ProductionCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProductionCommand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductionCommand) GetSourceEventIds() []string {
	if x != nil {
		return x.SourceEventIds
	}
	return nil
}

func (x *ProductionCommand) GetRequiresManagerConfirmation() bool {
	if x != nil {
		return x.RequiresManagerConfirmation
	}
	return false
}

func (x *ProductionCommand) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *ProductionCommand) GetPayload() isProductionCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProductionCommand) GetPlayWalkupMusic() *PlayWalkupMusicPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductionCommand_PlayWalkupMusic); ok {
			return x.PlayWalkupMusic
		}
	}
	return nil
}

func (x *ProductionCommand) GetUpdateScoreboard() *UpdateScoreboardPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductionCommand_UpdateScoreboard); ok {
			return x.UpdateScoreboard
		}
	}
	return nil
}

func (x *ProductionCommand) GetGenerateCommentary() *GenerateCommentaryPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductionCommand_GenerateCommentary); ok {
			return x.GenerateCommentary
		}
	}
	return nil
}

func (x *ProductionCommand) GetTriggerAlert() *TriggerAlertPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductionCommand_TriggerAlert); ok {
			return x.TriggerAlert
		}
	}
	return nil
}

type isProductionCommand_Payload interface {
	isProductionCommand_Payload()
}

type ProductionCommand_PlayWalkupMusic struct {
	PlayWalkupMusic *PlayWalkupMusicPayload `protobuf:"bytes,9,opt,name=play_walkup_music,json=playWalkupMusic,proto3,oneof"`
}

type ProductionCommand_UpdateScoreboard struct {
	UpdateScoreboard *UpdateScoreboardPayload `protobuf:"bytes,10,opt,name=update_scoreboard,json=updateScoreboard,proto3,oneof"`
}

type ProductionCommand_GenerateCommentary struct {
	GenerateCommentary *GenerateCommentaryPayload `protobuf:"bytes,11,opt,name=generate_commentary,json=generateCommentary,proto3,oneof"`
}

type ProductionCommand_TriggerAlert struct {
	TriggerAlert *TriggerAlertPayload `protobuf:"bytes,12,opt,name=trigger_alert,json=triggerAlert,proto3,oneof"`
}

func (*ProductionCommand_PlayWalkupMusic) isProductionCommand_Payload() {}

func (*ProductionCommand_UpdateScoreboard) isProductionCommand_Payload() {}

func (*ProductionCommand_GenerateCommentary) isProductionCommand_Payload() {}

func (*ProductionCommand_TriggerAlert) isProductionCommand_Payload() {}

var File_dugout_v1_production_command_proto protoreflect.FileDescriptor

const file_dugout_v1_production_command_proto_rawDesc = "" +
	"\n" +
	"\"dugout/v1/production_command.proto\x12\tdugout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\x16PlayWalkupMusicPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1c\n" +
	"\n" +
	"fade_in_ms\x18\x03 \x01(\x05R\bfadeInMs\x12&\n" +
	"\x0fmax_duration_ms\x18\x04 \x01(\x05R\rmaxDurationMs\"\xe1\x02\n" +
	"\x17UpdateScoreboardPayload\x12\x1d\n" +
	"\n" +
	"home_score\x18\x01 \x01(\x05R\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\x02 \x01(\x05R\tawayScore\x12\x16\n" +
	"\x06inning\x18\x03 \x01(\x05R\x06inning\x12\x15\n" +
	"\x06is_top\x18\x04 \x01(\bR\x05isTop\x12\x14\n" +
	"\x05balls\x18\x05 \x01(\x05R\x05balls\x12\x18\n" +
	"\astrikes\x18\x06 \x01(\x05R\astrikes\x12\x12\n" +
	"\x04outs\x18\a \x01(\x05R\x04outs\x12\x1f\n" +
	"\vbatter_name\x18\b \x01(\tR\n" +
	"batterName\x12!\n" +
	"\fpitcher_name\x18\t \x01(\tR\vpitcherName\x12&\n" +
	"\x0fpitch_speed_mph\x18\n" +
	" \x01(\x02R\rpitchSpeedMph\x12)\n" +
	"\x10display_template\x18\v \x01(\tR\x0fdisplayTemplate\"p\n" +
	"\x19GenerateCommentaryPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12 \n" +
	"\ftts_asset_id\x18\x02 \x01(\tR\n" +
	"ttsAssetId\x12\x1d\n" +
	"\n" +
	"play_audio\x18\x03 \x01(\bR\tplayAudio\"\x8b\x01\n" +
	"\x13TriggerAlertPayload\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\tR\talertType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\"\xb0\x05\n" +
	"\x11ProductionCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\x10source_event_ids\x18\x06 \x03(\tR\x0esourceEventIds\x12B\n" +
	"\x1drequires_manager_confirmation\x18\a \x01(\bR\x1brequiresManagerConfirmation\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.dugout.v1.CommandStatusR\x06status\x12O\n" +
	"\x11play_walkup_music\x18\t \x01(\v2!.dugout.v1.PlayWalkupMusicPayloadH\x00R\x0fplayWalkupMusic\x12Q\n" +
	"\x11update_scoreboard\x18\n" +
	" \x01(\v2\".dugout.v1.UpdateScoreboardPayloadH\x00R\x10updateScoreboard\x12W\n" +
	"\x13generate_commentary\x18\v \x01(\v2$.dugout.v1.GenerateCommentaryPayloadH\x00R\x12generateCommentary\x12E\n" +
	"\rtrigger_alert\x18\f \x01(\v2\x1e.dugout.v1.TriggerAlertPayloadH\x00R\ftriggerAlertB\t\n" +
	"\apayload*\xbd\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMAND_STATUS_QUEUED\x10\x01\x12\x1a\n" +
	"\x16COMMAND_STATUS_STARTED\x10\x02\x12\x1c\n" +
	"\x18COMMAND_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18COMMAND_STATUS_CANCELLED\x10\x05BKZIgithub.com/Aniket25042003/Dugout/packages/contracts/go/dugout/v1;dugoutv1b\x06proto3"

var (
	file_dugout_v1_production_command_proto_rawDescOnce sync.Once
	file_dugout_v1_production_command_proto_rawDescData []byte
)

func file_dugout_v1_production_command_proto_rawDescGZIP() []byte {
	file_dugout_v1_production_command_proto_rawDescOnce.Do(func() {
		file_dugout_v1_production_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dugout_v1_production_command_proto_rawDesc), len(file_dugout_v1_production_command_proto_rawDesc)))
	})
	return file_dugout_v1_production_command_proto_rawDescData
}

var file_dugout_v1_production_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dugout_v1_production_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dugout_v1_production_command_proto_goTypes = []any{
	(CommandStatus)(0),                // 0: dugout.v1.CommandStatus
	(*PlayWalkupMusicPayload)(nil),    // 1: dugout.v1.PlayWalkupMusicPayload
	(*UpdateScoreboardPayload)(nil),   // 2: dugout.v1.UpdateScoreboardPayload
	(*GenerateCommentaryPayload)(nil), // 3: dugout.v1.GenerateCommentaryPayload
	(*TriggerAlertPayload)(nil),       // 4: dugout.v1.TriggerAlertPayload
	(*ProductionCommand)(nil),         // 5: dugout.v1.ProductionCommand
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_dugout_v1_production_command_proto_depIdxs = []int32{
	6, // 0: dugout.v1.ProductionCommand.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: dugout.v1.ProductionCommand.status:type_name -> dugout.v1.CommandStatus
	1, // 2: dugout.v1.ProductionCommand.play_walkup_music:type_name -> dugout.v1.PlayWalkupMusicPayload
	2, // 3: dugout.v1.ProductionCommand.update_scoreboard:type_name -> dugout.v1.UpdateScoreboardPayload
	3, // 4: dugout.v1.ProductionCommand.generate_commentary:type_name -> dugout.v1.GenerateCommentaryPayload
	4, // 5: dugout.v1.ProductionCommand.trigger_alert:type_name -> dugout.v1.TriggerAlertPayload
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_dugout_v1_production_command_proto_init() }
func file_dugout_v1_production_command_proto_init() {
	if File_dugout_v1_production_command_proto != nil {
		return
	}
	file_dugout_v1_production_command_proto_msgTypes[4].OneofWrappers = []any{
		(*ProductionCommand_PlayWalkupMusic)(nil),
		(*ProductionCommand_UpdateScoreboard)(nil),
		(*ProductionCommand_GenerateCommentary)(nil),
		(*ProductionCommand_TriggerAlert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dugout_v1_production_command_proto_rawDesc), len(file_dugout_v1_production_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dugout_v1_production_command_proto_goTypes,
		DependencyIndexes: file_dugout_v1_production_command_proto_depIdxs,
		EnumInfos:         file_dugout_v1_production_command_proto_enumTypes,
		MessageInfos:      file_dugout_v1_production_command_proto_msgTypes,
	}.Build()
	File_dugout_v1_production_command_proto = out.File
	file_dugout_v1_production_command_proto_goTypes = nil
	file_dugout_v1_production_command_proto_depIdxs = nil
}
