// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/audit.proto

/* eslint-disable */

export interface AuditRecord {
  auditId: string;
  gameId: string;
  /** e.g. "game_start", "manual_override", "failed_command" */
  actionType: string;
  /** e.g. "system", "manager_user_id" */
  actorId: string;
  /** e.g. "game_event", "cv_observation", "production_command" */
  entityType: string;
  entityId: string;
  description: string;
  /** Raw JSON for arbitrary structure storage */
  payloadJson: string;
  createdAt: Date | undefined;
}
