// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/common.proto

/* eslint-disable */

export enum TeamSide {
  TEAM_SIDE_UNSPECIFIED = 0,
  TEAM_SIDE_HOME = 1,
  TEAM_SIDE_AWAY = 2,
  UNRECOGNIZED = -1,
}

export interface BoundingBox {
  /** Normalized top-left x (0.0 - 1.0) */
  x: number;
  /** Normalized top-left y (0.0 - 1.0) */
  y: number;
  /** Normalized width (0.0 - 1.0) */
  width: number;
  /** Normalized height (0.0 - 1.0) */
  height: number;
}

export interface PlayerReference {
  id: string;
  name: string;
  jerseyNumber: string;
  teamId: string;
}
