// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/cv_observation.proto

/* eslint-disable */
import type { BoundingBox, TeamSide } from "./common";

export interface JerseyNumberPayload {
  jerseyNumber: string;
  teamSide: TeamSide;
  bbox: BoundingBox | undefined;
  trackId: string;
}

export interface PlayerLocalizationPayload {
  trackId: string;
  bbox: BoundingBox | undefined;
  teamSide: TeamSide;
}

export interface ModelMetadata {
  name: string;
  version: string;
  runtime: string;
}

export interface CvObservation {
  observationId: string;
  gameId: string;
  cameraId: string;
  observedAt:
    | Date
    | undefined;
  /** e.g. "jersey_number", "player_localization" */
  observationType: string;
  confidence: number;
  model: ModelMetadata | undefined;
  jerseyNumber?: JerseyNumberPayload | undefined;
  playerLocalization?: PlayerLocalizationPayload | undefined;
}
