// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/game_event.proto

/* eslint-disable */

export enum PitchResultType {
  PITCH_RESULT_TYPE_UNSPECIFIED = 0,
  PITCH_RESULT_TYPE_BALL = 1,
  PITCH_RESULT_TYPE_STRIKE_LOOKING = 2,
  PITCH_RESULT_TYPE_STRIKE_SWINGING = 3,
  PITCH_RESULT_TYPE_FOUL = 4,
  PITCH_RESULT_TYPE_PUT_IN_PLAY = 5,
  PITCH_RESULT_TYPE_HIT_BY_PITCH = 6,
  UNRECOGNIZED = -1,
}

export enum PlayOutcomeType {
  PLAY_OUTCOME_TYPE_UNSPECIFIED = 0,
  PLAY_OUTCOME_TYPE_OUT = 1,
  PLAY_OUTCOME_TYPE_SINGLE = 2,
  PLAY_OUTCOME_TYPE_DOUBLE = 3,
  PLAY_OUTCOME_TYPE_TRIPLE = 4,
  PLAY_OUTCOME_TYPE_HOME_RUN = 5,
  PLAY_OUTCOME_TYPE_WALK = 6,
  PLAY_OUTCOME_TYPE_REACHED_ON_ERROR = 7,
  PLAY_OUTCOME_TYPE_FIELDERS_CHOICE = 8,
  UNRECOGNIZED = -1,
}

export enum ClockAction {
  CLOCK_ACTION_UNSPECIFIED = 0,
  CLOCK_ACTION_START = 1,
  CLOCK_ACTION_STOP = 2,
  CLOCK_ACTION_RESET = 3,
  UNRECOGNIZED = -1,
}

export interface PitchResultPayload {
  result: PitchResultType;
  pitcherId: string;
  batterId: string;
  speedMph: number;
}

export interface PlayOutcomePayload {
  type: PlayOutcomeType;
  runsScored: number;
  outsRecorded: number;
  batterId: string;
  description: string;
}

export interface InningTransitionPayload {
  inningNumber: number;
  /** true = top, false = bottom */
  isTop: boolean;
}

export interface SubstitutionPayload {
  teamId: string;
  playerInId: string;
  playerOutId: string;
  position: string;
}

export interface ClockControlPayload {
  action: ClockAction;
  setTimeSeconds: number;
}

export interface GameCorrectionPayload {
  balls: number;
  strikes: number;
  outs: number;
  homeScore: number;
  awayScore: number;
  reason: string;
}

export interface ManualOverridePayload {
  /** e.g. "confirm_player_identity" */
  overrideType: string;
  /** e.g. observation ID or command ID */
  originalId: string;
  selectedPlayerId: string;
  reason: string;
}

export interface GameEvent {
  eventId: string;
  gameId: string;
  /** e.g. "referee_app", "manager_dashboard" */
  source: string;
  sourceDeviceId: string;
  occurredAt: Date | undefined;
  receivedAt: Date | undefined;
  sequence: number;
  confidence: number;
  /** "official" or "manager" */
  authority: string;
  correlationId: string;
  pitchResult?: PitchResultPayload | undefined;
  playOutcome?: PlayOutcomePayload | undefined;
  inningTransition?: InningTransitionPayload | undefined;
  substitution?: SubstitutionPayload | undefined;
  clockControl?: ClockControlPayload | undefined;
  correction?: GameCorrectionPayload | undefined;
  manualOverride?: ManualOverridePayload | undefined;
}
