// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/game_state.proto

/* eslint-disable */

export interface GameState {
  gameId: string;
  balls: number;
  strikes: number;
  outs: number;
  homeScore: number;
  awayScore: number;
  inning: number;
  isTop: boolean;
  runnerOnFirst: boolean;
  runnerOnFirstPlayerId: string;
  runnerOnSecond: boolean;
  runnerOnSecondPlayerId: string;
  runnerOnThird: boolean;
  runnerOnThirdPlayerId: string;
  activeBatterId: string;
  activePitcherId: string;
  /** Current 1-based index in the lineup (1-9) */
  battingIndexHome: number;
  /** Current 1-based index in the lineup (1-9) */
  battingIndexAway: number;
  gameClockSeconds: number;
  isClockRunning: boolean;
  lastEventId: string;
  updatedAt: Date | undefined;
}
