// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: dugout/v1/production_command.proto

/* eslint-disable */

export enum CommandStatus {
  COMMAND_STATUS_UNSPECIFIED = 0,
  COMMAND_STATUS_QUEUED = 1,
  COMMAND_STATUS_STARTED = 2,
  COMMAND_STATUS_COMPLETED = 3,
  COMMAND_STATUS_FAILED = 4,
  COMMAND_STATUS_CANCELLED = 5,
  UNRECOGNIZED = -1,
}

export interface PlayWalkupMusicPayload {
  playerId: string;
  assetId: string;
  fadeInMs: number;
  maxDurationMs: number;
}

export interface UpdateScoreboardPayload {
  homeScore: number;
  awayScore: number;
  inning: number;
  isTop: boolean;
  balls: number;
  strikes: number;
  outs: number;
  batterName: string;
  pitcherName: string;
  pitchSpeedMph: number;
  /** 'batter_intro', 'pitcher_intro', 'count', etc. */
  displayTemplate: string;
}

export interface GenerateCommentaryPayload {
  text: string;
  ttsAssetId: string;
  playAudio: boolean;
}

export interface TriggerAlertPayload {
  /** "low_cv_confidence", "duplicate_event", etc. */
  alertType: string;
  message: string;
  confidence: number;
  /** The ID of the event or observation causing the alert */
  entityId: string;
}

export interface ProductionCommand {
  commandId: string;
  gameId: string;
  /** "play_walkup_music", "update_scoreboard", etc. */
  commandType: string;
  /** "music_adapter", "graphics_adapter", etc. */
  target: string;
  createdAt: Date | undefined;
  sourceEventIds: string[];
  requiresManagerConfirmation: boolean;
  status: CommandStatus;
  playWalkupMusic?: PlayWalkupMusicPayload | undefined;
  updateScoreboard?: UpdateScoreboardPayload | undefined;
  generateCommentary?: GenerateCommentaryPayload | undefined;
  triggerAlert?: TriggerAlertPayload | undefined;
}
