-- Migration: Down (000001_init_schema)

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS production_commands CASCADE;
DROP TABLE IF EXISTS cv_observations CASCADE;
DROP TABLE IF EXISTS game_events CASCADE;
DROP TABLE IF EXISTS lineup_entries CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS media_assets CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
